MyName = "Sans";
MyHP = 667;
MyMaxHP = 667;
CheckDescription[0] = "* Sans - 10 ATK 67 DEF&* He looks prepared for anything,&  but isn't taking it seriously?";
CheckDescription[1] = "* Maybe it's just a trick.&* Let's just get it over with.";
Act[0] = "Check";
Act[1] = "Taunt";
ShowHealthBar = true;
CanSpare = false;
